const $=s=>document.querySelector(s);const fmtDate=v=>v?new Date(v).toLocaleString('ko-KR',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'—';
function tick(){const d=new Date();$('#clock').textContent=d.toLocaleTimeString('ko-KR',{hour12:false});$('#footerTime').textContent=d.toLocaleString('ko-KR')}tick();setInterval(tick,1000);const monitored=['크레스트','묵수','신수','수채화','펄퍼스','잉크','성수','융화'];
const systemHealthState={drive:null,script:null,notion:null,deploy:null};
const alertState={drive:null,script:null,notion:null,deploy:null};
function renderAlertCenter(){
  const box=$('#alertCenter');if(!box)return;
  const issues=[];
  if(alertState.script==='error')issues.push({level:'error',title:'Apps Script 오류',message:'최근 Apps Script 실행에 실패가 감지되었습니다.',href:'#engine'});
  else if(alertState.script==='warning')issues.push({level:'warning',title:'Apps Script 경고',message:'최근 Apps Script 실행이 건너뛰어졌거나 경고 상태입니다.',href:'#engine'});
  if(alertState.notion==='error')issues.push({level:'error',title:'Notion 동기화 오류',message:'최근 Notion 동기화가 실패했습니다.',href:'#notion'});
  if(alertState.deploy==='error')issues.push({level:'error',title:'배포 오류',message:'최근 GitHub Pages 배포 결과를 확인해야 합니다.',href:'#deploy'});
  else if(alertState.deploy==='warning')issues.push({level:'warning',title:'배포 진행 중',message:'GitHub Pages 배포가 아직 완료되지 않았습니다.',href:'#deploy'});
  if(alertState.drive==='error')issues.push({level:'error',title:'Drive 상태 오류',message:'자동화 상태 데이터를 정상적으로 불러오지 못했습니다.',href:'#series'});
  if(!issues.length){box.hidden=true;box.className='alert-center hidden';return}
  const first=issues.find(x=>x.level==='error')||issues[0];
  const errors=issues.filter(x=>x.level==='error').length;
  const warnings=issues.filter(x=>x.level==='warning').length;
  box.hidden=false;box.className='alert-center '+(first.level==='error'?'':'warn-state');
  $('#alertTitle').textContent=errors?('SYSTEM ALERT · '+errors+' ERROR'+(errors>1?'S':'')):('SYSTEM NOTICE · '+warnings+' WARNING'+(warnings>1?'S':''));
  $('#alertMessage').textContent=issues.map(x=>x.title).join(' · ');
  $('#alertAction').href=first.href;
}
function serviceHealth(series){const active=series.filter(x=>x.driveStatus==='ok').length;return series.length?Math.round(active/series.length*100):0}
function updateOverallHealth(){const parts=Object.values(systemHealthState).filter(v=>typeof v==='number');if(!parts.length)return;const score=Math.round(parts.reduce((a,b)=>a+b,0)/parts.length);$('#healthScore').textContent=score;$('#healthLine').style.width=score+'%';let badge='OPERATIONAL',cls='good',copy='Drive · Apps Script · Notion · GitHub Deploy가 정상 범위입니다.';if(score<100&&score>=75){badge='DEGRADED';cls='warn';copy='일부 구성요소가 경고 또는 진행 상태입니다. 아래 서비스별 상태를 확인하세요.'}if(score<75){badge='ATTENTION';cls='bad';copy='하나 이상의 핵심 구성요소에 문제가 감지되었습니다. 아래 관제 패널을 확인하세요.'}$('#healthBadge').textContent=badge;$('#healthBadge').className='status '+cls;$('#healthCopy').textContent=copy}
function renderStatus(s){const all=(s.series||[]).filter(x=>x.name!=='자동화 상태');const target=monitored.map(n=>all.find(x=>x.name===n)).filter(Boolean);const score=serviceHealth(target);systemHealthState.drive=score;alertState.drive=score===100?'ok':'warning';updateOverallHealth();renderAlertCenter();$('#todayTotal').textContent=s.todayTotal??'—';$('#archiveTotal').textContent=all.reduce((a,x)=>a+(x.totalCount||0),0);$('#seriesTotal').textContent=all.length;$('#lastSync').textContent='SYNC '+fmtDate(s.updatedAt);$('#scheduleLabel').textContent='SCHEDULE '+(s.schedule||[]).join(' / ');$('#seriesGrid').innerHTML=target.map(x=>`<article class="series-card"><div class="row"><b>${x.name}</b><i class="dot"></i></div><strong>${x.todayCount??0}<small> TODAY</small></strong><small>${x.lastFile||'최근 파일 없음'}</small><small>${fmtDate(x.lastSavedAt)} · TOTAL ${x.totalCount??0}</small></article>`).join('');const pipe=[['Drive folders',target.filter(x=>x.driveStatus==='ok').length,target.length],['Today output',target.reduce((a,x)=>a+(x.todayCount||0),0),Math.max(1,(s.dailyPlanned||16))],['Series reporting',target.filter(x=>x.lastResult==='success').length,target.length],['Archive index',all.filter(x=>x.totalCount>0).length,all.length]];$('#pipeline').innerHTML=pipe.map(([n,v,m])=>`<div class="pipe-row"><b>${n}</b><div class="bar"><i style="width:${Math.min(100,Math.round(v/m*100))}%"></i></div><span>${v} / ${m}</span></div>`).join('');const events=[...all].filter(x=>x.lastSavedAt).sort((a,b)=>new Date(b.lastSavedAt)-new Date(a.lastSavedAt)).slice(0,10);$('#activityList').innerHTML=events.map(x=>`<div class="event"><time>${new Date(x.lastSavedAt).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit',hour12:false})}</time><span class="tag">${x.name}</span><b>${x.lastFile}</b><em>DRIVE OK</em></div>`).join('')||'<p class="muted">최근 이벤트가 없습니다.</p>'}
function renderUsage(d){const s=d.summary||{};$('#logSuccessRate').textContent=(s.successRate??0).toFixed(1)+'%';$('#logRuns').textContent=s.runs??0;$('#logFailed').textContent=s.failed??0;$('#logRegens').textContent=s.regenerations??0;$('#usageSync').textContent='LOG SYNC '+fmtDate(d.generatedAt);$('#reliability').innerHTML=(d.series||[]).map(x=>{const rate=x.runs?Math.round(x.success/x.runs*100):0;return `<div class="rel-row"><span>${x.name}</span><div class="bar"><i style="width:${rate}%"></i></div><b>${rate}%</b><small>${x.avgElapsed?Math.round(x.avgElapsed)+'s':'—'}</small></div>`}).join('');$('#runTable').innerHTML=(d.recentRuns||[]).map(x=>`<div class="run-row"><time>${x.time.slice(5,16)}</time><b>${x.series}</b><span class="${x.result==='success'?'good':'bad'}">${x.result.toUpperCase()}</span><small>GEN ${x.generationAttempts} · RE ${x.regenerations} · ${x.elapsedSeconds??'—'}s</small></div>`).join('')}
function renderScript(d){const a=d.appsScript||{},r=a.lastRun||{},ok=d.overallStatus==='ok'&&r.result==='success';$('#scriptBadge').textContent=ok?'OPERATIONAL':d.overallStatus==='warning'?'WARNING':'ERROR';$('#scriptBadge').className='status '+(ok?'good':d.overallStatus==='warning'?'warn':'bad');$('#scriptFunction').textContent=r.functionName||'—';$('#scriptResult').textContent=(r.result||'—').toUpperCase();$('#scriptResult').className=ok?'good':'bad';$('#scriptDuration').textContent=Number.isFinite(r.durationMs)?(r.durationMs/1000).toFixed(2)+'s':'—';$('#scriptFailures').textContent=a.consecutiveFailures??'—';$('#scriptStarted').textContent=fmtDate(r.startedAt);$('#scriptFinished').textContent=fmtDate(r.finishedAt);$('#scriptSync').textContent=fmtDate(d.updatedAt);$('#scriptError').textContent=r.error||'No runtime error reported.';$('#scriptError').className=r.error?'bad':'muted';$('#scriptService').textContent=ok?'CONNECTED':d.overallStatus==='warning'?'WARNING':'ERROR';$('#scriptService').className='pill '+(ok?'good':d.overallStatus==='warning'?'warn':'bad');systemHealthState.script=ok?100:(d.overallStatus==='warning'?75:0);alertState.script=ok?'ok':(d.overallStatus==='warning'?'warning':'error');updateOverallHealth();renderAlertCenter()}
function renderNotion(d){const n=d.notionSync||{},ok=n.lastResult==='success';$('#notionBadge').textContent=ok?'OPERATIONAL':n.lastResult?'ERROR':'NO DATA';$('#notionBadge').className='status '+(ok?'good':n.lastResult?'bad':'neutral');$('#notionResult').textContent=(n.lastResult||'—').toUpperCase();$('#notionResult').className=ok?'good':n.lastResult?'bad':'';$('#notionSeries').textContent=n.lastSeries||'—';$('#notionDuration').textContent=Number.isFinite(n.durationMs)?(n.durationMs/1000).toFixed(2)+'s':'—';$('#notionFailures').textContent=n.consecutiveFailures??'—';$('#notionArtwork').textContent=n.lastArtwork||'—';$('#notionStarted').textContent=fmtDate(n.startedAt);$('#notionFinished').textContent=fmtDate(n.finishedAt);$('#notionError').textContent=n.error||'No Notion sync error reported.';$('#notionError').className=n.error?'bad':'muted';$('#notionService').textContent=ok?'CONNECTED':n.lastResult?'ERROR':'NO DATA';$('#notionService').className='pill '+(ok?'good':n.lastResult?'bad':'neutral');systemHealthState.notion=ok?100:(n.lastResult?0:50);alertState.notion=ok?'ok':(n.lastResult?'error':'warning');updateOverallHealth();renderAlertCenter()}
function renderGithubSnapshot(d){
  const g=d.githubDeploy||{},runs=g.recentRuns||[],commits=g.recentCommits||[],latest=g.latestRun||runs[0]||null;
  $('#commitCount').textContent=commits.length||'—';
  $('#commits').innerHTML=commits.length?commits.slice(0,6).map(c=>`<div class="commit"><b>${c.message||'Commit'}</b><small>${String(c.sha||'').slice(0,7)} · ${fmtDate(c.date)}</small></div>`).join(''):'<p class="muted">저장된 GitHub 스냅샷이 없습니다.</p>';
  const today=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Seoul'});
  const todayCount=commits.filter(c=>c.date&&new Date(c.date).toLocaleDateString('en-CA',{timeZone:'Asia/Seoul'})===today).length;
  $('#todayCommits').textContent=todayCount;
  $('#deployCancelled').textContent=runs.filter(x=>x.conclusion==='cancelled').length;
  $('#deployResult').textContent=latest?(latest.conclusion||latest.status||'—').toUpperCase():'—';
  $('#deploySha').textContent=latest&&latest.head_sha?latest.head_sha.slice(0,7):'—';
  $('#deployStarted').textContent=latest?fmtDate(latest.run_started_at||latest.created_at):'—';
  $('#deployFinished').textContent=latest?fmtDate(latest.updated_at):'—';
  const dur=latest&&latest.updated_at&&(latest.run_started_at||latest.created_at)?Math.max(0,(new Date(latest.updated_at)-new Date(latest.run_started_at||latest.created_at))/1000):null;
  $('#deployDuration').textContent=dur!==null?Math.round(dur)+'s':'—';
  $('#deployMessage').textContent=latest&&latest.message?latest.message:(commits[0]&&commits[0].message)||'저장된 커밋 정보 없음';
  const deployOk=latest&&latest.status==='completed'&&latest.conclusion==='success';
  $('#deployBadge').textContent=deployOk?'OPERATIONAL':latest&&latest.status!=='completed'?'DEPLOYING':'ATTENTION';
  $('#deployBadge').className='status '+(deployOk?'good':latest&&latest.status!=='completed'?'warn':'bad');
  $('#deployHealth').textContent=deployOk?'저장된 최신 GitHub Pages 배포가 정상 완료되었습니다.':latest&&latest.status!=='completed'?'저장된 최신 배포가 진행 상태입니다.':'저장된 최신 배포 결과를 확인해야 합니다.';
  $('#deployHealth').className=deployOk?'good':latest&&latest.status!=='completed'?'warn':'bad';
  $('#githubService').textContent=deployOk?'CONNECTED':'CHECK DEPLOY';
  $('#githubService').className='pill '+(deployOk?'good':'warn');
  systemHealthState.deploy=deployOk?100:(latest&&latest.status!=='completed'?75:0);
  alertState.deploy=deployOk?'ok':(latest&&latest.status!=='completed'?'warning':'error');
  updateOverallHealth();renderAlertCenter();
}
async function loadStatus(){try{const r=await fetch('automation-status.json?ts='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('status');renderStatus(await r.json());$('#driveService').textContent='CONNECTED'}catch(e){$('#healthBadge').textContent='DATA ERROR';$('#healthBadge').className='status bad';$('#healthCopy').textContent='automation-status.json을 불러오지 못했습니다.';$('#driveService').textContent='CHECK DATA';$('#driveService').className='pill bad';systemHealthState.drive=0;alertState.drive='error';updateOverallHealth();renderAlertCenter()}}
async function loadUsage(){try{const r=await fetch('system-usage.json?ts='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('usage');renderUsage(await r.json())}catch(e){$('#usageSync').textContent='LOG DATA ERROR';$('#runTable').innerHTML='<p class="muted">진단 로그 데이터를 불러오지 못했습니다.</p>'}}
async function loadScript(){try{const r=await fetch('system-status.json?ts='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('script');const d=await r.json();renderScript(d);renderNotion(d);renderGithubSnapshot(d)}catch(e){$('#scriptBadge').textContent='DATA ERROR';$('#scriptBadge').className='status bad';$('#scriptService').textContent='UNAVAILABLE';$('#scriptService').className='pill bad';$('#scriptError').textContent='system-status.json을 불러오지 못했습니다.';systemHealthState.script=0;systemHealthState.notion=0;alertState.script='error';alertState.notion='error';updateOverallHealth();renderAlertCenter()}}
async function loadGithub(){try{const r=await fetch('system-status.json?ts='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('status');renderGithubSnapshot(await r.json())}catch(e){$('#githubService').textContent='UNAVAILABLE';$('#githubService').className='pill warn';$('#deployBadge').textContent='DATA ERROR';$('#deployBadge').className='status bad';$('#deployHealth').textContent='로컬 SYSTEM 상태 파일을 불러오지 못했습니다.';systemHealthState.deploy=0;alertState.deploy='error';updateOverallHealth();renderAlertCenter()}}
async function refresh(){const b=$('#refresh');b.disabled=true;b.textContent='↻ SYNCING';await Promise.all([loadStatus(),loadUsage(),loadScript(),loadGithub()]);b.disabled=false;b.textContent='↻ REFRESH'}$('#refresh').addEventListener('click',refresh);refresh();setInterval(()=>Promise.all([loadStatus(),loadUsage(),loadScript()]),60000);const navLinks=[...document.querySelectorAll('nav a')];
navLinks.forEach(a=>a.addEventListener('click',()=>{navLinks.forEach(x=>x.classList.remove('active'));a.classList.add('active')}));
const sectionMap=navLinks.map(a=>({a,id:a.getAttribute('href').slice(1),el:document.querySelector(a.getAttribute('href'))})).filter(x=>x.el);
const scrollSpy=new IntersectionObserver(entries=>{
  const visible=entries.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];
  if(!visible)return;
  const item=sectionMap.find(x=>x.el===visible.target);if(!item)return;
  navLinks.forEach(x=>x.classList.toggle('active',x===item.a));
},{rootMargin:'-18% 0px -68% 0px',threshold:[0,.1,.25,.5]});
sectionMap.forEach(x=>scrollSpy.observe(x.el));